#:kivy 1.10.1

#:import DropDown kivy.uix.dropdown
#:import Button kivy.uix.button

<DrinksDropDown@DropDown>:
    Button:
        text: "Американо"
        size_hint_y:None
        on_release: root.select("Американо")
    Button:
        text: "Капучино"
        size_hint_y:None
        on_release: root.select("Капучино")
    Button:
        text: "Латте"
        size_hint_y:None
        on_release: root.select("Латте")
